baseurl = "https://example.com/"
title = "よくある質問"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    custom_css = ["/css/custom_main.css"]
    
[outputs]
    home = ["JSON","HTML"]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]
