baseurl = "https://example.com/"
title = "FAQ"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags
    
[outputs]
    home = ["JSON","HTML"]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]
