baseurl = "https://bizoope.github.io/faq/"
title = "FAQ"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags
    
[outputs]
    home = ["JSON","HTML"]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[params]
    categories = [
        "アカウント",
        "管理者",
        "その他",
        "ID-POS分析",
        "POS分析",
    ]