baseurl = "https://example.com/"
title = "FAQ"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    custom_css = ["/css/custom_main.css"]
    footer_css = ["/css/custom_footer.css"]
    
[outputs]
    home = ["JSON","HTML"]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]
